
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhaXNrMjAwMUBnbWFpbC5jb20iLCJzdGFmZklkIjoiNjYwNmI4NDY1NjYwYzdhZWExMjE4NzBjIiwiaWF0IjoxNzEyODY0MTMzLCJleHAiOjE3MTI4Njc3MzN9.-6DHy72shOeNb3FatjntnVvzjDBIwZyDdoThpMteE-4

{
    "name": "Kenny",
    "email": "laisk2001@gmail.com",
    "password":"123456",
    "role":"admin"
}
###
POST  http://3.144.232.16:3000/api/staff/login HTTP/1.1
content-type: application/json

{
    "email": "laisk2001@gmail.com",
    "password":"123456"
}
###


PATCH http://localhost:3000/api/staff/update/66058fe4596fa2f453f8f2bc HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    
    "email": "laisk2001@gmail.com",
    "password":"123456"
}

###
DELETE http://localhost:3000/api/staff/delete/66058fe4596fa2f453f8f2bc HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    
    "email": "laisk2001@gmail.com",
    "password":"123456"
}

###
GET http://localhost:3000/api/devices/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Kenny",
    "email": "laisk2001@gmail.com",
    "password":"123456",
    "role":"admin"
}

###
GET http://localhost:3000/api/devices/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Kenny",
    "email": "laisk2001@gmail.com",
    "password":"123456",
    "role":"admin"
}

###
POST http://localhost:3000/api/devices/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "device-01",
    "serialNumber": "LoRa-02",
    "location":"Cheung Chau"
}
###
PUT http://localhost:3000/api/devices/660e9e5d021d0683abb82aeb HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "status": "active",
    "dateTimeOfActivation":"2024-04-03T08:48:50.073+00:00"
    
}
###
DELETE http://localhost:3000/api/devices/6606b8e95660c7aea121871a HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "LORA-01",
    "serialNumber": "LoRa-03",
    "location":"Cheung Chau"
}


###
POST http://localhost:3000/api/lockers/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "lockerId": "Locker-01"
}

###
GET http://localhost:3000/api/lockers/Locker-0/availability HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "lockerId": "Locker-01"
}
###
POST http://localhost:3000/api/lockers/Locker-01/access HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "tagUid": "1304fa12"
}
###
POST http://localhost:3000/api/lockers/match HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "tagUid": "1304fa12",
    "lockerId": "Locker-01"
}


###
POST http://localhost:3000/api/lockers/Locker-0/release HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "tagUid": "1304fa12",
    "lockerId": "Locker-01"
}

###
POST  http://localhost:3000/api/devicesData/data HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "deviceId":"device-01", 
    "position": 
    {"beacon1":-22, "beacon2":-35, "beacon3": -45, "beacon4":-35}
}

###
GET  http://44.202.236.163:3000/api/devicesData/active HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhaXNrMjAwMUBnbWFpbC5jb20iLCJzdGFmZklkIjoiNjYwNmI4NDY1NjYwYzdhZWExMjE4NzBjIiwiaWF0IjoxNzEyODY0MTMzLCJleHAiOjE3MTI4Njc3MzN9.-6DHy72shOeNb3FatjntnVvzjDBIwZyDdoThpMteE-4

{
    "deviceId":"device-01", 
    "position": 
    {"beacon1":-22, "beacon2":-35, "beacon3": -45, "beacon4":-35}, 
    "heartrate":10
}
###
GET  http://localhost:3000/api/alerts/alerts HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "deviceId":"device-01", 
    "position": 
    {"beacon1":-22, "beacon2":-35, "beacon3": -45, "beacon4":-35}, 
    "heartrate":10
}